apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |
    concurrent = 4
    check_interval = 3
    log_level = "info"

    [[runners]]
      name = "buildah-runner"
      url = "https://gitlab.com/"
      token = "YOUR_REGISTRATION_TOKEN_HERE"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        privileged = true
        image = "quay.io/buildah/stable"
        [[runners.kubernetes.volumes.empty_dir]]
          name = "containers-storage"
          mount_path = "/var/lib/containers"
        [[runners.kubernetes.volumes.empty_dir]]
          name = "run-storage"
          mount_path = "/run"
        [[runners.kubernetes.volumes.empty_dir]]
          name = "tmp-storage"
          mount_path = "/tmp"
