apiVersion: v1
kind: Secret
metadata:
  name: harbor-cred
  namespace: gitlab-runner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG_JSON_HERE
# Alternatively, create via kubectl:
# kubectl create secret docker-registry harbor-cred \
#  --docker-server=<HARBOR_REGISTRY_URL> \
#  --docker-username=<USERNAME> \
#  --docker-password=<PASSWORD> \
#  --docker-email=<EMAIL> \
#  -n gitlab-runner
